# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


main:
  - name: 首页
    url: ''
    weight: 10

  - name: 病例
    url: 'examples'
    weight: 30

  - name: 学术专著
    url: 'publications'
    weight: 40

  - name: 联系方式
    url: 'contact'
    weight: 60




# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: Curriculum Vitae
#    url: uploads/leonelli_mauro.pdf
#    weight: 50
